
alias getannakarenina='wget https://www.gutenberg.org/cache/epub/1399/pg1399.txt -O annakarenina.txt'
alias y='yt-dlp'
alias la='ls -la'
alias l='ls -l'
alias ip='ip -c'
alias unclutter='grep -vE "^$|^\s*#"'
alias mypath='echo $PATH | tr ":" "\n"'
alias fp="dpkg -l | grep -i"
alias simpleserver='python3 -m http.server 8000'
alias mkv2mp4='ffmpeg -i input.mkv -c:v copy -c:a copy -c:s mov_text -map 0 output.mp4'
alias makevenv='python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip && pip install jedi flake8 yapf]'
#alias vimhelp='less /home/thomasgrusz/Documents/Computerscience/sysadmin_files/vim.txt'
#alias downloadytplaylist='yt-dlp --yes-playlist -o "%(playlist_index)s - %(title)s.%(ext)s"'
#alias startpythonproject='python3 -m venv venv && source venv/bin/activate && pip install flake8 autopep8'
#alias startwebproject='npm install eslint-plugin-html --save-d --save-dev && npx eslint --init && cp ~/.myscripts/tern-project-template ./.tern-project'
